services:
  - type: web
    name: animefavs-web
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app.wsgi:app
    envVars:
      - key: FLASK_APP
        value: app:create_app('production')
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.12
      - key: SECRET_KEY
        sync: false
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: FLASKY_MAIL_SUBJECT_PREFIX
        value: '[AnimeFavs]'
      - key: FLASKY_MAIL_SENDER
        value: 'AnimeFavs Admin <seu-email@gmail.com>'
      - key: DATABASE_URL
        fromDatabase:
          name: animefavs-db
          property: connectionString
    autoDeploy: true

databases:
  - type: psql
    name: animefavs-db
    plan: free
    region: oregon
    disk:
      sizeGB: 1